### ISSUE TITLE
Blackboard AMI instance to test LTI

### ISSUE THREAD

**Issue by abanghendri** [blackboard/anthologydevdocs#104]
Hi, I don't know where is the right place to post this question, so I post it here.

I use official AMI of blackboard on my AWS EC2 instance to test our LTI integration, we have successfully integrated our tool with moodle so know we want to try integrate it at blackboard, I register my tool on developer.anthology.com and place given URLs from developer portal to our tool just like usual LTI integration process.

All the process went good, our tool is displayed when using deep linking content selection and select content, after that my Blackboard instance always shows error and says "unable to load tool configuration".

I don't get any issus on my tool side, is that caused by wrong return URL? (I mean, on developer portal I got http://developer.blackboard.com..... for any URL such as JWKS, token, and so on), how to find my instance URLs for that case?

any help would be appreciate, thanks

**Comment by AGuyWorking** [comment]
Apologies for the stale issue, if the issue persists or any other issue arises, please fill a Behind the Blackboard ticket (if you're a client) or email us with the issue to developers@anthology.com
